name: Frontend CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: 拉取代码
        uses: actions/checkout@v2

      - name: 安装 Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: 安装依赖
        run: npm install

      - name: 构建
        run: npm run build:prod

      - name: 部署到远程服务器
        run: |
          echo "开始上传前端 dist..."
          scp -r dist/* root@47.108.195.148:/root/data/ruoyi/ruoyi-font/nginx/html/
          echo "✅ 前端部署完成！"
